collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7688172
  brandStrength: 0.5
  lightness: 0.765233
  brandColors:
    - '#000000'
  rhythmicContrast: 1
typography_spectrum: 0.3817204
layout_spectrum: 1
name: RobMarin
