collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3817204
color:
  saturation: 0.5340502
  brandStrength: 0.5
  lightness: 0.530466
  brandColors:
    - '#000000'
  rhythmicContrast: 0.5573477
layout_spectrum: 0.9569892
name: RobMarin
